server.port=8080

spring.application.name=api-gateway

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=https://super-duper-potato-q647r999j7rc4xp5-8081.app.github.dev
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=5
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}

spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=https://super-duper-potato-q647r999j7rc4xp5-8082.app.github.dev
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/orders/**



# Log file
logging.file.name=logs/api-gateway.log

# Log level
logging.level.com.example.gateway=INFO

